{{- if .Values.create_ip }}
{{- if not .Values.disabled }}

apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: {{ include "ip_name" $ }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "gke_project_id" . }}
spec:
  location: global
  ipVersion: IPV4

{{- end }}
{{- end }}
