{{- if .Values.create_dns }}
{{- if not .Values.disabled }}

apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: {{ include "lifecycle" $ -}}-dns-record
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "dns_project_id" . }}
spec:
  name: "{{- include "domain" . -}}."
  type: "A"
  ttl: 8600
  managedZoneRef:
    external: ignite-dns-zone
  rrdatas:
  - {{ required "REQUIRED: google.ip_address" .Values.google.ip_address }}

{{- end }}
{{- end }}
