{{- if .Values.admin_iam }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin-iam
  namespace: {{ $.Values.namespace }}
  labels:
    tier: iam
    tenant_code: admin
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $.Values.root_project }}
  destination:
    server: {{ $.Values.destination.server }}
    namespace: admin-iam
  source:
    chart: admin-iam
    repoURL: {{ $.Values.charts_url }}
    targetRevision: 0.0.2
    helm:
      values: |
        admin_sa: {{ include "admin_sa" $ }}
        admin_folder_id: {{ include "admin_folder_id" $ }}
        sa_project_id: {{ include "sa_project_id" $ }}
        dns_project_id: {{ include "dns_project_id" $ }}
        gke_project_id: {{ include "gke_project_id" $ }}
        db_project_id: {{ include "db_project_id" $ }}
        app_project_id: {{ include "app_project_id" $ }}
        tenants: {{ print "\n" }}{{ .Values.tenants | toYaml | indent 10 }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false

{{- end }}
