{{- if .Values.app_infra }}

{{- range .Values.tenants }}
{{- $tenant := . }}

{{- range .apps }}
{{- $app := . }}
{{- if $app.enabled }}

{{- range .lifecycles }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $tenant.name -}}-{{- $app.name -}}-{{- .name -}}-infra
  namespace: {{ $.Values.namespace }}
  labels:
    tier: infra
    tenant: {{ $tenant.name }}
    app: {{ $app.name }}
    lifecycle: {{ .name }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $.Values.root_project }}
  destination:
    server: {{ $.Values.destination.server }}
    namespace: {{ $tenant.name -}}-{{- $app.name -}}-{{- .name -}}-infra
  source:
    chart: app-infra
    repoURL: {{ $.Values.charts_url }}
    targetRevision: 0.0.1
    helm:
      values: |
        sa_project_id: {{ include "sa_project_id" $ }}
        dns_project_id: {{ include "dns_project_id" $ }}
        gke_project_id: {{ include "gke_project_id" $ }}
        db_project_id: {{ include "db_project_id" $ }}
        app_project_id: {{ include "app_project_id" $ }}
        github_org: {{ required "REQUIRED: github_org" $.Values.github_org }}
        tenant_code: {{ $tenant.name }}
        app_code: {{ $app.name }}
        domain: {{ $app.domain }}
        lifecycle: {{ .name }}
        disabled: {{ .disabled }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false

---

{{- end }}

{{- end }}
{{- end }}

{{- end }}
{{- end }}
