{{- if .Values.events }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: {{ .Values.namespace }}
  labels:
    tier: platform
    service: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.root_project }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: argo-events
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-events
    targetRevision: 1.5.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false

{{- end }}
