{{- if .Values.workflows }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: {{ .Values.namespace }}
  labels:
    tier: service
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.root_project }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: argo-workflows
  source:
    chart: argo-workflows
    repoURL: {{ $.Values.charts_url }}
    targetRevision: 0.0.5
    helm:
      values: |
        ip_admin_sa: {{ include "dns_admin_sa" $ }}
        gke_project_id: {{ include "gke_project_id" $ }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false

{{- end }}
