{{- if .Values.argocd }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: {{ $.Values.namespace }}
  labels:
    tier: platform
    service: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ required "REQUIRED: root_project" $.Values.root_project }}
  destination:
    server: {{ required "REQUIRED: destination.server" $.Values.destination.server }}
    namespace: {{ required "REQUIRED: namespace" $.Values.namespace }}
  source:
    repoURL: {{ include "repo_url" . }}
    path: charts/argocd
    targetRevision: main
    helm:
      values: |
        ip_admin_sa: {{ include "dns_admin_sa" $ }}
        gke_project_id: {{ include "gke_project_id" $ }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PruneLast=false

{{- end }}
