{{ if .Values.backstage }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  labels:
    deployment: cluster
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: root-project
  destination:
    server: {{ .Values.destination.server }}
    namespace: backstage
  source:
    repoURL: {{ .Values.charts_url }}
    chart: backstage
    targetRevision: 0.0.1
    helm:
      values: |
        gcp_project_id: {{ include "gke_project_id" $ }}
        app_admin_sa: {{ include "admin_sa" $ }}
        github_org: {{ required "REQUIRED: github_org" $.Values.github_org }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false

{{- end }}

