{{- if .Values.config }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config
  namespace: {{ $.Values.namespace }}
  labels:
    tier: config
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $.Values.root_project }}
  destination:
    server: {{ $.Values.destination.server }}
    namespace: cluster-config
  source:
    chart: cluster-config
    repoURL: {{ $.Values.charts_url }}
    targetRevision: 0.0.3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PruneLast=false

{{- end }}
