{{ if .Values.crossplane }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  labels:
    deployment: cluster
    service: iac
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  ignoreDifferences:
  - group: rbac.authorization.k8s.io 
    kind: ClusterRole
    name: crossplane
    jsonPointers:
    - /rules
  project: root-project
  destination:
    server: {{ .Values.destination.server }}
    namespace: crossplane-system
  source:
    chart: crossplane
    targetRevision: 1.7.0
    repoURL: https://charts.crossplane.io/stable
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false

---

{{- if .Values.crossplane_addons }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-addons
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  labels:
    deployment: cluster
    service: iac
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.destination.server }}
    namespace: crossplane-system
  project: root-project
  source:
    repoURL: {{ $.Values.charts_url }}
    chart: crossplane-addons
    targetRevision: 0.0.1
    helm:
      values: |
        admin_sa: {{ include "admin_sa" $ }}
        gcp_project_id: {{ include "gke_project_id" $ }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PruneLast=false

{{- end }}

{{- end }}

