{{ if .Values.external_secrets }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: {{ $.Values.namespace }}
  labels:
    tier: platform
    tier: service
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $.Values.root_project }}
  destination:
    server: {{ $.Values.destination.server }}
    namespace: external-secrets
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.4.4
    helm:
      values: |
        serviceAccount:
          annotations:
            iam.gke.io/gcp-service-account: {{ include "admin_sa" $ }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false

---

{{- end }}
