{{- if .Values.gatekeeper }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper
  namespace: {{ .Values.namespace }}
  labels:
    tier: security
    service: opa
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.root_project }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: gatekeeper-system
  source:
    chart: gatekeeper
    repoURL: {{ $.Values.charts_url }}
    targetRevision: 0.0.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false

{{- end }}
