{{- if .Values.linkerd }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: {{ .Values.namespace }}
  labels:
    tier: platform
    service: mesh
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.root_project }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: linkerd
  source:
    repoURL: https://helm.linkerd.io/stable 
    chart: linkerd2
    targetRevision: 2.11.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false

{{- end }}
