
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "ignite-pops-party-project-xdr"
  name: computeaddress-sample-global
  labels:
    label-one: "value-one"
spec:
  addressType: EXTERNAL
  description: a test global address
  location: global
  ipVersion: IPV4
