ingress: false

argo-cd:
  installCRDs: false
  global:
    image:
      tag: v2.1.6
  dex:
    enabled: false
  server:
    service:
      type: ClusterIP
    extraArgs:
      - --insecure
    config:
      accounts.viewer: login
      accounts.app-viewer: login

      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
