{{- if .Values.enabled }}
{{- if .Values.dns }}

apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: {{ include "ip_name" . }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "gke_project" . }}
spec:
  location: global
  ipVersion: IPV4

---

apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: {{ .Values.lifecycle -}}-dns-record
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "dns_project" . }}
spec:
  name: "{{- include "domain" . -}}."
  type: "A"
  ttl: 8600
  managedZoneRef:
    external: anthos-dns-zone
  rrdatas:
  - {{ required "REQUIRED: google.ip_address" .Values.google.ip_address }}

{{- end }}
{{- end }}
