{{- range .Values.tenants }}
{{- $tenant := . }}
{{- range .apps }}
{{- $app := . }}

{{- range .lifecycles }}

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: {{ $tenant.name -}}-{{- $app.name -}}-{{- .name -}}-admin
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "sa_project_id" $ }}
spec:
  displayName: "{{ $tenant.name  }} {{  $app.name  }} {{ .name }} admin service account"

---

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: {{ $tenant.name -}}-{{- $app.name -}}-{{- .name -}}-admin-wi
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "gke_project_id" $ }}
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: {{ $tenant.name -}}-{{- $app.name -}}-{{- .name -}}-admin
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:{{- include "gke_project_id" $ -}}.svc.id.goog[cnrm-system/cnrm-controller-manager-{{ $tenant.name -}}-{{- $app.name -}}-{{- .name -}}-iam]

---


{{- end }}
{{- end }}
{{- end }}
