apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata: # kpt-merge: /gcp-provider
  name: gcp-provider
spec:
  serviceAccountName: gcp-provider
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata: # kpt-merge: /kubernetes-provider
  name: kubernetes-provider
spec:
  serviceAccountName: kubernetes-provider
