{{- if false }}

apiVersion: batch/v1beta1
kind: CronJob
metadata: # kpt-merge: /crossplane-gcp-credentials-sync
  name: crossplane-gcp-credentials-sync
spec:
  suspend: false
  schedule: "*/45 * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: kubernetes-provider
          restartPolicy: Never
          containers:
          - image: google/cloud-sdk
            name: create-secret
            env:
            - name: SERVICE_ACCOUNT
              value: {{ include "admin_sa" . }}
            imagePullPolicy: IfNotPresent
            command:
            - /bin/bash
            - -ce
            - "kubectl create secret generic gcp-creds \\\n  --dry-run=client \\\n  --from-literal=token=\"$(curl -H \"Metadata-Flavor: Google\" http://169.254.169.254/computeMetadata/v1/instance/service-accounts/$SERVICE_ACCOUNT/token)\" \\\n  -o yaml | kubectl apply -f -"

{{- end }}
