apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata: # kpt-merge: /crossplane-provider-gcp
  name: crossplane-provider-gcp
spec:
  package: crossplane/provider-gcp:v0.20.0
  controllerConfigRef:
    name: gcp-provider
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata: # kpt-merge: /crossplane-provider-kubernetes
  name: crossplane-provider-kubernetes
spec:
  package: crossplane/provider-kubernetes:v0.3.0
  controllerConfigRef:
    name: kubernetes-provider
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata: # kpt-merge: /crossplane-provider-helm
  name: crossplane-provider-helm
spec:
  package: crossplane/provider-helm:v0.10.0
  controllerConfigRef:
    name: kubernetes-provider
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata: # kpt-merge: /in-cluster
  name: in-cluster
spec:
  credentials:
    source: InjectedIdentity
