apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: /gcp-provider
  name: gcp-provider
  annotations:
    iam.gke.io/gcp-service-account: {{ include "admin_sa" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: /kubernetes-provider
  name: kubernetes-provider
  annotations:
    iam.gke.io/gcp-service-account: {{ include "admin_sa" . }}
