{{- if .Values.config }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config
  namespace: {{ $.Values.namespace }}
  labels:
    tier: config
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $.Values.root_project }}
  destination:
    server: {{ $.Values.destination.server }}
    namespace: cluster-config
  source:
    path: charts/cluster-config
    repoURL: {{ include "repo_url" $ }}
    targetRevision: {{ include "targetRevision" $ }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PruneLast=false

---

{{- if false }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-cluster-config
  namespace: {{ $.Values.namespace }}
  labels:
    tier: config
    tier: platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $.Values.root_project }}
  destination:
    server: {{ $.Values.destination.prod_server }}
    namespace: cluster-config
  source:
    path: charts/cluster-config
    repoURL: {{ include "repo_url" $ }}
    targetRevision: {{ include "targetRevision" $ }}
    helm:
      values: |
        use_config_connector: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PruneLast=false

{{- end }}

{{- end }}
