{{- if .Values.gatekeeper }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper
  namespace: {{ .Values.namespace }}
  labels:
    tier: service
    tier: security
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.root_project }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: gatekeeper-system
  source:
    path: charts/gatekeeper
    repoURL: {{ include "repo_url" . }}
    targetRevision: {{ include "targetRevision" . }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false

{{- end }}
