{{- if .Values.nginx }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: {{ .Values.namespace }}
  labels:
    tier: platform
    tier: service
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.root_project }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: nginx-ingress
  source:
    repoURL: https://helm.nginx.com/stable
    chart: nginx-ingress
    targetRevision: 0.12.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false

{{- end }}
