{{- if .Values.rbac_manager }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac-manager
  namespace: {{ .Values.namespace }}
  labels:
    tier: service
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.root_project }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: rbac-manager
  source:
    repoURL: https://charts.fairwinds.com/stable 
    chart: rbac-manager
    targetRevision: 1.11.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false

{{- end }}
