{{- if .Values.google.config_connector.pg_database.enabled }}

apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: backstage4-pg
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "gcp_project" . }}
spec:
  databaseVersion: POSTGRES_9_6
  region: us-central1
  settings:
    tier: db-custom-1-3840
    availabilityType: REGIONAL

{{- end }}
