apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sIngressService
metadata:
  name: ingress-check-service
spec:
  match:
    kinds:
      - apiGroups: ["extensions", "networking.k8s.io"]
        kinds: ["Ingress"]