apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRestrictNamespaces
metadata:
  name: restrict-namespace
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    restrictedNamespaces: 
      - "default"
      - "kube-public"
      - "config-management-system"
      - "config-management-monitoring"
      - "cnrm-system"
      - "configconnector-operator-system"
      - "gatekeeper-system"
      - "kube-system"
      - "kube-node-lease"
      - "resource-group-system"
      - "twistlock"
