{{- if and (.Values.enabled) (.Values.autoscaler.enabled) }}

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: api-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-dep
  minReplicas: {{ .Values.api.replicas }}
  maxReplicas: {{ .Values.api.max_replicas }}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageValue: {{ .Values.api.target_mem }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.api.target_cpu }}

{{- end }}
