{{- if .Values.ingress -}}

apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"ports": {"http":"backendconfig"}}'
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/name: prometheus-grafana

{{- end }}



