{{- range $.Values.apps }}
{{- $app := . }}

{{- if .enabled }}

{{- range .lifecycles }}
{{- if not .disabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "tenant_code" $ -}}-{{- $app.name -}}-{{- .name -}}-app
  namespace: {{ .Values.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ include "tenant_code" $ -}}-project
  destination:
    namespace: {{ include "tenant_code" $ -}}-{{- $app.name -}}-{{- .name -}}-app
    server: {{ $.Values.server }}
  source:
    chart: walker-web-app
    repoURL: {{ include "helm_repo_url" $ }}
    targetRevision: {{ include "target_revision" $ }}
    # path: charts/web-app
    # repoURL: "git@github.com:{{- $.Values.github_org -}}/{{- include "app_repo_name" $ -}}"
    helm:
      values: |
        app_project_id: {{ include "app_project_id" $ }}
        sa_project_id: {{ include "sa_project_id" $ }}
        tenant_code: {{ include "tenant_code" $ }}
        app_code: {{ $app.name }}
        domain: {{ $app.domain }}
        lifecycle: {{ .name }}
        google:
          ingress:
            enabled: true
        nginx_ingress:
          enabled: false
          https: true
        cert_manager:
          enabled: false
        external_dns:
          enabled: true
        external_secrets:
          enabled: true
      # valueFiles:
      #   - values/{{- .name -}}.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false

---

{{- end }}

{{- end }}

{{- end }}
{{- end }}


