
security_policy: us-only
ssl_policy: tls-12

repo_name: backstage

cluster_name: primary-cluster

github:
  enabled: true
  oauth: true

external_secrets:
  enabled: true
  workload_identity:
    enabled: false

external_dns:
  enabled: true

registry_name: gcr.io

pd:
  enabled: true
  size: 20Gi

google:
  region: us-central1
  oauth: false
  iap: false
  sql_instance: backstage-instance
  artifact_repo_name: backstage-images
  ip_name: backstage-ip
  config_connector:
    enabled: true
    context:
      enabled: false
    cloudbuild:
      enabled: true
    address:
      enabled: false
    artifact_registry:
      enabled: false
    cloud_sql:
      enabled: false

jira:
  enabled: true

argocd:
  enabled: true

frontend:
  enabled: false
  replicaCount: 1
  image:
    tag: latest
    pullPolicy: IfNotPresent
  containerPort: 80
  resources:
    requests:
      memory: 128Mi
    limits:
      memory: 256Mi

backend:
  enabled: true
  nodeEnv: development
  replicaCount: 1
  image:
    tag: latest
    pullPolicy: IfNotPresent
  containerPort: 7007
  postgresCertMountEnabled: true
  resources:
    requests:
      memory: 512Mi
    limits:
      memory: 1024Mi

nameOverride: ''
fullnameOverride: ''

issuer:
  email:
  clusterIssuer: 'letsencrypt-staging'

appConfig:
  app:
    title: Backstage
  auth:
    providers:
      google:
        development:
          appOrigin: 'http://localhost:3000/'
          secure: false
          clientId: ${AUTH_GOOGLE_CLIENT_ID}
          clientSecret: ${AUTH_GOOGLE_CLIENT_SECRET}
      github:
        development:
          appOrigin: 'http://localhost:3000/'
          secure: false
          clientId: ${AUTH_GITHUB_CLIENT_ID}
          clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
          enterpriseInstanceUrl: ${AUTH_GITHUB_ENTERPRISE_INSTANCE_URL}
      gitlab:
        development:
          appOrigin: 'http://localhost:3000/'
          secure: false
          clientId: ${AUTH_GITLAB_CLIENT_ID}
          clientSecret: ${AUTH_GITLAB_CLIENT_SECRET}
          audience: ${GITLAB_BASE_URL}
      okta:
        development:
          appOrigin: 'http://localhost:3000/'
          secure: false
          clientId: ${AUTH_OKTA_CLIENT_ID}
          clientSecret: ${AUTH_OKTA_CLIENT_SECRET}
          audience: ${AUTH_OKTA_AUDIENCE}
      oauth2:
        development:
          appOrigin: 'http://localhost:3000/'
          secure: false
          clientId: ${AUTH_OAUTH2_CLIENT_ID}
          clientSecret: ${AUTH_OAUTH2_CLIENT_SECRET}
          authorizationURL: ${AUTH_OAUTH2_AUTH_URL}
          tokenURL: ${AUTH_OAUTH2_TOKEN_URL}
      auth0:
        development:
          clientId: ${AUTH_AUTH0_CLIENT_ID}
          clientSecret: ${AUTH_AUTH0_CLIENT_SECRET}
          domain: ${AUTH_AUTH0_DOMAIN}
      microsoft:
        development:
          clientId: ${AUTH_MICROSOFT_CLIENT_ID}
          clientSecret: ${AUTH_MICROSOFT_CLIENT_SECRET}
          tenantId: ${AUTH_MICROSOFT_TENANT_ID}

