
security_policy: us-only
ssl_policy: tls-12

domain: backstage.igniteme.dev

gcp_project_id: project-x-bootstrap
repo_name: backstage

github:
  enabled: true
  oauth: true

external_dns:
  enabled: true

registry_name: gcr.io

google:
  region: us-central1
  oauth: true
  iap: true
  config_connector: true
  create_ip: true
  create_registry: false
  create_db: false
  sql_instance: backstage-instance
  artifact_repo_name: backstage-images
  ip_name: backstage-ip

jira:
  enabled: true

argocd:
  enabled: true

frontend:
  enabled: false
  replicaCount: 1
  image:
    tag: latest
    pullPolicy: IfNotPresent
  containerPort: 80
  resources:
    requests:
      memory: 128Mi
    limits:
      memory: 256Mi

backend:
  enabled: true
  nodeEnv: development
  replicaCount: 1
  image:
    tag: latest
    pullPolicy: IfNotPresent
  containerPort: 7007
  postgresCertMountEnabled: true
  resources:
    requests:
      memory: 512Mi
    limits:
      memory: 1024Mi

nameOverride: ''
fullnameOverride: ''

issuer:
  email:
  clusterIssuer: 'letsencrypt-staging'

appConfig:
  app:
    title: Backstage
