{{- if .Values.backend.enabled }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backstage.fullname" . }}-backend-app-config
data:
{{ include "backstage.appConfigFilename" . | indent 2 }}: |
{{ tpl (.Files.Get "files/app-config.backend.development.yaml.tpl") . | indent 4 }}

---
{{- end }}

