
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: secret-store
  namespace: {{ .Release.Namespace }}
spec:
  # controller: {{ .Values.app_code }}
  provider:
    gcpsm:
      projectID: {{ include "app_project" $ }}

---

apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "backstage.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: {{ include "backstage.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    {{- if .Values.github.enabled }}
    - secretKey: GITHUB_TOKEN 
      remoteRef:
        key: github-token
    {{- end }}

    {{- if .Values.github.oauth }}
    - secretKey: AUTH_GITHUB_CLIENT_ID
      remoteRef:
        key: github-oauth-id
    - secretKey: AUTH_GITHUB_CLIENT_SECRET
      remoteRef:
        key: github-oauth-secret
    {{- end }}

    {{- if .Values.google.oauth }}
    - secretKey: AUTH_GOOGLE_CLIENT_ID
      remoteRef:
        key: google-oauth-id
    - secretKey: AUTH_GOOGLE_CLIENT_SECRET
      remoteRef:
        key: google-oauth-secret
    {{- end }}

    {{- if .Values.jira.enabled }}
    - secretKey: JIRA_TOKEN 
      remoteRef:
        key: jira-token
    {{- end }}


    {{- if .Values.argocd.enabled }}
    - secretKey: ARGOCD_AUTH_TOKEN 
      remoteRef:
        key: argocd-token
    {{- end }}


{{- if .Values.google.iap }}
---

apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: oauth-credentials
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: oauth-credentials
    creationPolicy: Owner
  data:
  - secretKey: client_id
    remoteRef:
      key: google-oauth-id
  - secretKey: client_secret
    remoteRef:
      key: google-oauth-secret

{{- end }}

