{{- if .Values.external_secrets.enabled }}

apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: backstage-secret-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    gcpsm:
      projectID: {{ include "gcp_project" $ }}
      {{- if .Values.external_secrets.workload_identity.enabled }}
      auth:
        workloadIdentity:
          clusterLocation: {{ required "REQUIRED: google.region" .Values.google.region }}
          clusterName: {{ include "cluster_name" $ }}
          clusterProjectID: {{ include "gke_project" $ }}
          serviceAccountRef:
            name: backstage-secrets-sa
      {{- end }}

---

apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "backstage.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: SecretStore
    name: backstage-secret-store
  target:
    name: {{ include "backstage.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    {{- if .Values.github.enabled }}
    - secretKey: GITHUB_TOKEN 
      remoteRef:
        key: backstage-github-token
    {{- end }}

    {{- if .Values.github.oauth }}
    - secretKey: AUTH_GITHUB_CLIENT_ID
      remoteRef:
        key: backstage-github-oauth-id
    - secretKey: AUTH_GITHUB_CLIENT_SECRET
      remoteRef:
        key: backstage-github-oauth-secret
    {{- end }}

    {{- if .Values.google.oauth }}
    - secretKey: AUTH_GOOGLE_CLIENT_ID
      remoteRef:
        key: backstage-google-oauth-id
    - secretKey: AUTH_GOOGLE_CLIENT_SECRET
      remoteRef:
        key: backstage-google-oauth-secret
    {{- end }}

    {{- if .Values.jira.enabled }}
    - secretKey: JIRA_TOKEN 
      remoteRef:
        key: backstage-jira-token
    {{- end }}


    {{- if .Values.argocd.enabled }}
    - secretKey: ARGOCD_AUTH_TOKEN 
      remoteRef:
        key: backstage-argocd-token
    {{- end }}


{{- if .Values.google.iap }}
---

apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: oauth-credentials
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: SecretStore
    name: backstage-secret-store
  target:
    name: oauth-credentials
    creationPolicy: Owner
  data:
  - secretKey: client_id
    remoteRef:
      key: backstage-google-oauth-id
  - secretKey: client_secret
    remoteRef:
      key: backstage-google-oauth-secret

{{- end }}

{{- end }}
