{{- $appUrl := urlParse .Values.appConfig.app.baseUrl}}

apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: google-cert
  namespace: {{ .Release.Namespace }}
spec:
  domains:
    - {{ $appUrl.host }}

