{{- if .Values.google.create_registry }}

apiVersion: artifactregistry.cnrm.cloud.google.com/v1beta1
kind: ArtifactRegistryRepository
metadata:
  name: {{ include "artifact_repo_name" . }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "app_project" . }}
spec:
  format: DOCKER
  location: {{ .Values.google.region }}

{{- end }}
