
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ include "app_sa" . }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage-secrets-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ include "secrets_sa" . }}

