
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ include "app_sa" . }}.gserviceaccount.com

