{{- if .Values.ingress -}}

apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: argo-rollouts-frontendconfig
spec:
  sslPolicy: tls-12
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT

---

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: argo-rollouts-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /
    port: 3100

  {{- if .Values.use_iap }}
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: oauth-credentials
  {{- end }}

{{- end -}}
