{{- if .Values.ingress -}}

apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: argo-rollouts-cert
spec:
  domains:
    - {{ include "domain" . }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-rollouts-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: rollouts-ip
    networking.gke.io/managed-certificates: argo-rollouts-cert
    networking.gke.io/v1beta1.FrontendConfig: argo-rollouts-frontendconfig
    {{- if .Values.external_dns }}
    external-dns.alpha.kubernetes.io/hostname: {{ include "domain" . -}}.
    {{- end }}
spec:
  defaultBackend:
    service:
      name: argo-rollouts-svc
      port:
        number: 443

{{- end -}}
