enabled: true
local: false

branch: main

registry: gcr.io

notifications:
  email: walker.obrien@mavenwave.com

backend:
  enabled: true
  repo_name: ''
  build_context: .
  containerPort: 8000
  tag: latest
  label: server
  use_pd: false
  mount_pd: false
  disk_size: 5Gi

  memory:
    request: 64Mi
    limit: 256Mi
  cpu:
    request: .1
    limit: 1

  replicas: 1
  max_replicas: 5
  target_cpu: 80
  target_mem: 128Mi

frontend:
  enabled: true
  repo_name: ''
  build_context: .
  containerPort: 3000
  tag: latest
  memory:
    request: 5Mi
    limit: 50Mi
  cpu:
    request: .05
    limit: .5
  replicas: 1
  max_replicas: 3
  target_cpu: 80
  target_mem: 50Mi

google:
  region: us-central1
  zone: us-central1-a
  oauth: false
  artifact_repo_name: app-images
  config_connector:
    enabled: true
    context:
      enabled: false
    monitoring:
      alert:
        enabled: true
      dashboard:
        enabled: true
    cloudbuild:
      enabled: true
      machine_type: E2_HIGHCPU_8
    address:
      enabled: false
    artifact_registry:
      enabled: false
    sql:
      enabled: false
  ingress:
    enabled: true
    static_ip:
      enabled: false
    https: true
    mci: false
    primary: false
    use_failover: false
  iap:
    enabled: false
    test:
      enabled: false
  analytics:
    enabled: false

security_policy: us-only
ssl_policy: tls-12

oauth:
  google:
    enabled: false
    sheets:
      enabled: false
      path: /backend/secrets

  github:
    enabled: false

  facebook:
    enabled: false

  twitter:
    enabled: false

external_dns:
  enabled: true

external_secrets:
  enabled: false

ingress:
  enabled: true

nginx_ingress:
  enabled: false
  https: false

cert_manager:
  enabled: false

network_policy:
  enabled: false

autoscaler:
  enabled: false

cilium:
  enabled: false

django:
  enabled: false
  use_email: false

gin:
  input_path: /tmp/input
  enabled: false

db:
  proxy: false
  proxy_version: gcr.io/cloudsql-docker/gce-proxy:1.21.0

twilio:
  enabled: false
  flex:
    enabled: false

firebase:
  enabled: false

sendgrid:
  enabled: false

agile:
  enabled: false
  replicas: 1


