config_connector: false

argo-cd:
  fullnameOverride: argocd
  server:
    ingress:
      enabled: true
      ingressClassName: gce
      annotations: 
        kubernetes.io/ingress.global-static-ip-name: argocd-ip
        networking.gke.io/managed-certificates: argocd
        networking.gke.io/v1beta1.FrontendConfig: argocd

    service:
      annotations:
        cloud.google.com/neg: '{"ingress": true}'
        cloud.google.com/backend-config: '{"ports": {"http":"argocd"}}'

    GKEmanagedCertificate:
      enabled: true
      domains:
        - argocd.igniteme.dev
    GKEbackendConfig:
      enabled: true
      spec:
        securityPolicy:
          name: us-only
        iap:
          enabled: false
          oauthclientCredentials:
            secretName: oauth-credentials
        healthCheck:
          checkIntervalSec: 30
          timeoutSec: 5
          healthyThreshold: 1
          unhealthyThreshold: 2
          type: HTTP
          requestPath: /healthz
          port: 8080

    GKEfrontendConfig:
      enabled: true
      spec:
        sslPolicy: tls-12
        redirectToHttps:
          enabled: true
          responseCodeName: MOVED_PERMANENTLY_DEFAULT
  
  installCRDs: false
  global:
    image:
      tag: v2.1.6
  dex:
    enabled: false
  configs:
    knownHosts:
      data:
        ssh_known_hosts: |
          github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9CL3sd6oWoVzLMwRgHBCucs0GW/wJxcVt1+Oo+QoOQF3SJ7o4JhX5N5q3UjnLxJxxettxCybLgurfiiBXMmkB++OfO9CR626ItSsbAP6Bs23nD7/pvt9ebpGUnH7MkqpmnqKqvixGozZ7ZNXZzsMUCE+aoKgtyO3BMLwYMBBmv8OnqRnsaR6P+DrV7UHYVCNRaYNl21SZLdTbtNASRd3GmetuJVq9ZWf7vI3tdXCrMEAMdij//8dBAgdlD8Ub4Ea+vteQd2bPOzW8HXjFltroH0WSotTLMVMrjpYjlQDe1JGHRsbXGInYFu4fUCfMTNbsgwAoOHaeobq9cKtL0iEZ18c81HZiGJpaE0MfkuwzXJSJuiXoG4o7ZP+kH1Yoc5Ms4Hm3xwwhp4GVE3ExgRlKN8Glw948CByWcv9zHCRHZpisNBChDIa++qq6nM1CrKkwZNCvkmS5QYGHXNT5Cp5gQhiLwXBWGVWDaq7z31NQdSi4rohfLvaWRoCDnwZi4r0=

  server:
    service:
      type: ClusterIP
    extraArgs:
      - --insecure
    config:
      accounts.admin: apiKey
      accounts.viewer: login

      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
