{{- if .Values.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-dep
  labels:
    namespace: {{ .Release.Namespace }}
    app: api-dep
    tier: backend
spec:
  replicas: {{ required "REQUIRED: api.replicas" .Values.api.replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: api-dep
  template:
    metadata:
      labels:
        app: api-dep
    spec:
      {{- if .Values.api.use_pd }}
      volumes:
        - name: gce-volume
          persistentVolumeClaim:
            claimName: gce-pvc
      {{- end }}

      serviceAccountName: {{ include "ksa_name" . }}
      restartPolicy: Always
      containers:
      - name: api
        image: {{ include "api_image" . }}
        imagePullPolicy: Always

        {{- if and (.Values.django.enabled) (not .Values.db.proxy) (not .Values.api.use_pd) }}
        command: ["/bin/sh"]
        args: ["-c", "./init_db.sh && gunicorn -b 0.0.0.0:8000 api.wsgi"]
        {{- end }}

        {{- if .Values.api.use_pd }}
        volumeMounts:
          - mountPath: "/mnt"
            name: gce-volume
        {{- end }}

        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10

        env:
        - name: LIFECYCLE
          value: {{ .Values.lifecycle }}
        - name: USE_GCS
          value: "false"
        - name: DOMAIN
          value: {{ include "domain" . }}
        - name: GCP_PROJECT_ID
          value: {{ include "tenant_project_id" . }}
        - name: STATIC_BUCKET
          value: {{ include "bucket" . }}
        - name: SQL_DIR
          value: /mnt

        - name: DJANGO_KEY
        {{- if .Values.secrets.enabled }}
          valueFrom:
            secretKeyRef:
              name: secrets-manager
              key: fake-key
        {{- else }}
          value: fake-key-manual
        {{- end }}

        ports:
        - containerPort: 8000
          name: api-port

{{- end }}


