{{- if and (.Values.enabled) (not .Values.local) }}

{{- if .Values.ingress.https }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-tls
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ include "ip_name" . }}
    networking.gke.io/v1beta1.FrontendConfig: gke-frontendconfig
    {{- if .Values.external_dns.enabled }}
    external-dns.alpha.kubernetes.io/hostname: {{ include "domain" . -}}.
    {{- end -}}
    {{- if .Values.nginx_ingress.enabled }}
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    {{- end -}}

    {{- if .Values.cert_manager.enabled }}
    cert-manager.io/cluster-issuer: "letsencrypt-nginx"
    {{- else if .Values.ingress.cert }}
    networking.gke.io/managed-certificates: google-cert
    kubernetes.io/tls-acme: "true"
    {{- end }}
spec:
  {{- if .Values.cert_manager.enabled }}
  tls:
  - hosts:
    - {{ include "domain" $ }}
    secretName: ingress-certs
  {{- end }}
  defaultBackend:
    service:
      {{- if .Values.nginx.enabled }}
      name: nginx-svc
      port:
        number: 443
      {{- else }}
      name: api-svc
      port:
        number: 80
      {{- end }}

---

{{- end }}


{{- if .Values.ingress.http }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-http
  namespace: {{ .Release.Namespace }}
spec:
  defaultBackend:
    service:
      name: nginx-svc
      port:
        number: 443

{{- end }}

{{- end }}

