{{- if .Values.enabled }}
{{- if .Values.nginx.enabled }}

{{- $root := . }}

{{ range until (int .Values.num) }}

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    namespace: {{ $root.Values.namespace }}
    app: nginx-dep-{{- . }}
    tier: frontend
  name: nginx-dep-{{- . }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx-dep-{{- . }}
  template:
    metadata:
      labels:
        app: nginx-dep-{{- . }}
    spec:
      serviceAccountName: {{ include "ksa_name" $root }}
      containers:
      - name: nginx
        image: {{ include "nginx_image" $root }}
        imagePullPolicy: Always

        startupProbe:
          httpGet:
            path: /health/
            port: 80
          failureThreshold: 5
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /health/
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

        readinessProbe:
          httpGet:
            path: /health/
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

        env:
        - name: API_NAMESPACE
          value: {{ $root.Values.namespace }}
        - name: LIFECYCLE
          value: {{ required "REQUIRED: lifecycle" $root.Values.lifecycle }}
        - name: DOMAIN
          value: {{ include "domain" $root }}

        ports:
        - containerPort: 80
          name: https
          protocol: TCP

---

{{- end }}
{{- end }}
{{- end }}


