{{- if and (.Values.enabled) (.Values.secrets.enabled) }}

apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: secrets-manager
spec:
  controllerId: {{ .Values.tenant_code -}}-external-secrets
  backendType: gcpSecretsManager
  projectId: {{ include "tenant_project_id" . }}
  data:
    - key: fake-key
      name: fake-key
      version: latest
  template:
    metadata:
      labels:
        manager: secreter
{{- end }}


