{{- if and (.Values.enabled) (.Values.secrets.enabled) }}

apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: secrets-manager
  labels:
    manager: secreter
spec:
  controllerId: external-secrets-{{- .Values.tenant_code }}
  backendType: gcpSecretsManager
  projectId: {{ include "app_project" . }}
  data:
    - key: fake-key
      name: fake-key
      version: latest
  template:
    metadata:
      labels:
        manager: secreter
{{- end }}


