{{- if and (.Values.enabled) (.Values.frontend.enabled) }}

apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    tier: frontend
  {{- if not .Values.local }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "frontend-backendconfig"}'
  {{- end }}
spec:
  type: ClusterIP
  selector:
    app: frontend
    
  ports:
  - name: http
    port: 443
    targetPort: {{ .Values.frontend.containerPort }}

{{- end }}
