{{- if .Values.google.wi_test }}

apiVersion: v1
kind: Pod
metadata:
  name: gcloud
spec:
  serviceAccountName: app-sa
  containers:
  - image: google/cloud-sdk
    name: gcloud
    command: ["gcloud"]
    args: ["auth", "list"]

{{- end }}
