{{- if and (.Values.enabled) (not .Values.local) }}

{{- if .Values.ingress.https }}

apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: google-cert
spec:
  domains:
    - {{ include "domain" . }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-tls
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ include "ip_name" . }}
    networking.gke.io/managed-certificates: google-cert
    networking.gke.io/v1beta1.FrontendConfig: gke-frontendconfig
    {{- if .Values.external_dns.enabled }}
    external-dns.alpha.kubernetes.io/hostname: {{ include "subdomain" . -}}.
    {{- end }}
spec:
  rules:
  - http:
      paths:
      {{- if .Values.backend.enabled }}
      {{- if eq .Values.app_name "vcc" }}
      - path: /api/scheduling
      {{- else }}
      - path: /api
      {{- end }}
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 443
      {{- if .Values.django.enabled }}
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 443
      - path: /accounts
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 443
      {{- end }}
      {{- end }}

      {{- if .Values.frontend.enabled }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 443
      {{- end }}

---

{{- end }}

{{- end }}

