apiVersion: v1
kind: Secret
metadata:
  name: my-manual-secret
type: Opaque
data:
  password: {{ "fake-password" | b64enc }}

---

{{- if .Values.external_secrets.enabled }}

apiVersion: external-secrets.io/v1beta1 
kind: SecretStore
metadata:
  name: secret-store
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.google.project }}

---

{{- if .Values.firebase.enabled }}

apiVersion: external-secrets.io/v1beta1 
kind: ExternalSecret
metadata:
  name: firebase-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: firebase-secrets
    creationPolicy: Owner
  data:
  - secretKey: firebase-api-key
    remoteRef:
      key: firebase-api-key

---
{{- end }}

{{- if .Values.google.oauth.enabled }}

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth-credentials
spec:
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: oauth-credentials
    creationPolicy: Owner
  data:
  - secretKey: client_id
    remoteRef:
      key: oauth-id
  - secretKey: client_secret
    remoteRef:
      key: oauth-secret

---
{{- end }}

{{- if .Values.sendgrid.enabled }}

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sendgrid-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: sendgrid-secrets
    creationPolicy: Owner
  data:
  - secretKey: sendgrid-key
    remoteRef:
      key: sendgrid-key

---
{{- end }}

{{- if .Values.twilio.enabled }}

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: twilio-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: twilio-secrets
    creationPolicy: Owner
  data:
  - secretKey: twilio-account-sid
    remoteRef:
      key: twilio-account-sid
  - secretKey: twilio-auth-token
    remoteRef:
      key: twilio-auth-token

{{- end }}

{{- end }}

