{{- if .Values.ingress -}}

apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: google-cert
spec:
  domains:
    - {{ include "domain" . }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: vault-ip
    networking.gke.io/managed-certificates: google-cert
    networking.gke.io/v1beta1.FrontendConfig: frontendconfig
    {{- if .Values.external_dns }}
    external-dns.alpha.kubernetes.io/hostname: {{ include "domain" . -}}.
    {{- end }}
spec:
  defaultBackend:
    service:
      name: vault-ui-svc
      port:
        number: 8200

{{- end -}}
