{{- if .Values.ingress -}}

apiVersion: v1
kind: Service
metadata:
  name: vault-ui-svc
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "vault.chart" . }}
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    cloud.google.com/backend-config: '{"default": "backendconfig"}'
spec:
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
    component: server
  type: ClusterIP
  ports:
    - name: ui
      port: 8200
      targetPort: 8200

{{- end -}}

