{{- if .Values.context.enabled }}

apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnectorContext
metadata:
  name: configconnectorcontext.core.cnrm.cloud.google.com
spec:
  googleServiceAccount: {{ include "workspace_service_account" . }}

{{- end}}
