
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: {{ include "tenant_code" $ -}}-{{- include "app_code" $ -}}-{{- include "lifecycle" $ -}}-secrets
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "sa_project_id" $ }}
spec:
  displayName: "{{ include "lifecycle" $ }} {{ include "tenant_code" $ }} external secrets service account"

---

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: {{ include "tenant_code" $ -}}-{{- include "app_code" $ -}}-{{- include "lifecycle" $ -}}-secrets-wi
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "gke_project_id" $ }}
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: {{ include "tenant_code" $ -}}-{{- include "app_code" $ -}}-{{- include "lifecycle" $ -}}-secrets
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:{{- include "gke_project_id" $ -}}.svc.id.goog[{{- include "tenant_code" $ -}}-{{- include "app_code" $ -}}-external-secrets/{{- include "tenant_code" $ -}}-{{- include "app_code" $ -}}-external-secrets-kubernetes-external-secrets]


