
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: {{ .Release.Name -}}-secrets
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "sa_project_id" $ }}
spec:
  displayName: "{{- .Release.Name }} external secrets service account"

---

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: {{ .Release.Name -}}-secrets-wi
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "gke_project_id" $ }}
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: {{ .Release.Name -}}-secrets
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
      - serviceAccount:{{- include "gke_project_id" $ -}}.svc.id.goog[{{- required "REQUIRED: external_secrets.namespace" .Values.external_secrets.namespace -}}/{{- required "REQUIRED: external_secrets.ksa_name" .Values.external_secrets.ksa_name -}}]


