
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: {{ .Release.Name -}}-gke-partial-policy
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: {{ include "gke_project_id" $ }}
  bindings:
  - role: roles/monitoring.admin
    members:
    - memberFrom:
        serviceAccountRef:
          name: {{ .Release.Name -}}-infra
          namespace: {{ .Release.Namespace }}


---

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: {{ .Release.Name -}}-db-partial-policy
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: {{ include "db_project_id" $ }}
  bindings:
  - role: roles/cloudsql.client
    members:
    - memberFrom:
        serviceAccountRef:
          name: {{ .Release.Name -}}-workload
          namespace: {{ .Release.Namespace }}

  - role: roles/cloudsql.instanceUser
    members:
    - memberFrom:
        serviceAccountRef:
          name: {{ .Release.Name -}}-infra
          namespace: {{ .Release.Namespace }}


