
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: {{ include "tenant_code" $ -}}-{{- include "app_code" $ -}}-{{- include "lifecycle" $ -}}-gke-partial-policy
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: {{ include "gke_project_id" $ }}
  bindings:
    - role: roles/compute.publicIpAdmin
      members:
        - member: serviceAccount:{{ include "tenant_code" $ -}}-{{- include "app_code" $ -}}-{{- include "lifecycle" $ -}}-infra@{{- include "sa_project_id" $ -}}.iam.gserviceaccount.com
    - role: roles/monitoring.admin
      members:
        - member: serviceAccount:{{ include "tenant_code" $ -}}-{{- include "app_code" $ -}}-{{- include "lifecycle" $ -}}-infra@{{- include "sa_project_id" $ -}}.iam.gserviceaccount.com
    - role: roles/container.viewer
      members:
        - member: serviceAccount:{{ include "tenant_code" $ -}}-{{- include "app_code" $ -}}-{{- include "lifecycle" $ -}}-cicd@{{- include "app_project_id" $ -}}.iam.gserviceaccount.com

---

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: {{ include "tenant_code" $ -}}-{{- include "app_code" $ -}}-{{- include "lifecycle" $ -}}-db-partial-policy
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: {{ include "db_project_id" $ }}
  bindings:
    - role: roles/cloudsql.client
      members:
        - member: serviceAccount:{{ include "tenant_code" $ -}}-{{- include "app_code" $ -}}-{{- include "lifecycle" $ -}}-workload@{{- include "sa_project_id" $ -}}.iam.gserviceaccount.com
    - role: roles/cloudsql.instanceUser
      members:
        - member: serviceAccount:{{ include "tenant_code" $ -}}-{{- include "app_code" $ -}}-{{- include "lifecycle" $ -}}-infra@{{- include "sa_project_id" $ -}}.iam.gserviceaccount.com


