
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: {{ .Release.Name -}}-app-iam-policy
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: {{ include "app_project_id" $ }}
  bindings:
    - role: roles/artifactregistry.admin
      members:
      - memberFrom:
          serviceAccountRef:
            name: {{ .Release.Name -}}-infra
            namespace: {{ .Release.Namespace }}

    - role: roles/cloudbuild.builds.editor
      members:
      - memberFrom:
          serviceAccountRef:
            name: {{ .Release.Name -}}-infra
            namespace: {{ .Release.Namespace }}

    - role: roles/dns.admin
      members:
      - memberFrom:
          serviceAccountRef:
            name: {{ .Release.Name -}}-infra
            namespace: {{ .Release.Namespace }}

    - role: roles/iam.serviceAccountUser
      members:
      - memberFrom:
          serviceAccountRef:
            name: {{ .Release.Name -}}-infra
            namespace: {{ .Release.Namespace }}

    - role: roles/storage.admin
      members:
      - memberFrom:
          serviceAccountRef:
            name: {{ .Release.Name -}}-infra
            namespace: {{ .Release.Namespace }}

    - role: roles/storage.objectAdmin
      members:
      - memberFrom:
          serviceAccountRef:
            name: {{ .Release.Name -}}-workload
            namespace: {{ .Release.Namespace }}
      - memberFrom:
          serviceAccountRef:
            name: {{ .Release.Name -}}-cicd
            namespace: {{ .Release.Namespace }}

    - role: roles/logging.logWriter
      members:
      - memberFrom:
          serviceAccountRef:
            name: {{ .Release.Name -}}-workload
            namespace: {{ .Release.Namespace }}
      - memberFrom:
          serviceAccountRef:
            name: {{ .Release.Name -}}-cicd
            namespace: {{ .Release.Namespace }}

    - role: roles/errorreporting.writer
      members:
      - memberFrom:
          serviceAccountRef:
            name: {{ .Release.Name -}}-workload
            namespace: {{ .Release.Namespace }}

    - role: roles/monitoring.metricWriter
      members:
      - memberFrom:
          serviceAccountRef:
            name: {{ .Release.Name -}}-workload
            namespace: {{ .Release.Namespace }}

    - role: roles/artifactregistry.writer
      members:
      - memberFrom:
          serviceAccountRef:
            name: {{ .Release.Name -}}-cicd
            namespace: {{ .Release.Namespace }}

    - role: roles/secretmanager.secretAccessor
      members:
      - memberFrom:
          serviceAccountRef:
            name: {{ .Release.Name -}}-secrets
            namespace: {{ .Release.Namespace }}


