
{{ if .Values.github }}

apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  GITHUB_TOKEN: {{ default "none" .Values.github.token }}

{{ end }}

