
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: backstage-backendconfig
  namespace: {{ .Release.Namespace }}
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /
    port: {{ .Values.backend.containerPort }}
  securityPolicy:
    name: {{ .Values.backend.securityPolicy }}

  {{- if .Values.google.iap }}
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: oauth-credentials
  {{- end }}

