
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Values.backend.name }}-certificate
  namespace: {{ .Values.namespace }}
spec:
  domains:
    - {{ .Values.domainName }}

