
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.serviceName }}
  namespace: backstage
  annotations:
    cloud.google.com/backend-config: '{"default": "backstage-backendconfig"}'
    cloud.google.com/neg: '{"ingress": true}'

spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 7007
  selector:
    app: backstage

