
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}-service
  namespace: {{ .Values.namespace }}
  annotations:
    cloud.google.com/backend-config: '{"default": "backstage-backendconfig"}'
    cloud.google.com/neg: '{"ingress": true}'

spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: {{ .Values.backend.containerPort }}
  selector:
    app: {{ .Values.backend.name }}

