{{- if and (.Values.enabled) (.Values.backend.enabled) }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name -}}-backend-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name -}}-backend-svc
    tier: backend
  {{- if not .Values.local }}
  annotations:
    cloud.google.com/backend-config: '{"default": "gke-backendconfig"}'
  {{- end }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name -}}-backend-dep
    
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: {{ .Values.backend.containerPort }}

{{- end }}
