{{- if and (.Values.enabled) (.Values.backend.enabled) }}
{{- if not .Values.google.ingress.mci }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name -}}-backend-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name -}}-backend-svc
    tier: backend
  {{- if not .Values.local }}
  annotations:
    cloud.google.com/backend-config: '{"default": "gke-backendconfig"}'
    {{- if .Values.nginx_ingress.enabled }}
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- else }}
    cloud.google.com/neg: '{"ingress": true}'
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name -}}-backend-dep
    
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: {{ .Values.backend.containerPort }}

{{- end }}
{{- end }}
