{{- if and (.Values.enabled) (.Values.frontend.enabled) }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name -}}-frontend-dep
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name -}}-frontend-dep
    tier: frontend
spec:
  replicas: {{ required "REQUIRED: frontend.replicas" .Values.frontend.replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Release.Name -}}-frontend-dep
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        container.apparmor.security.beta.kubernetes.io/frontend: runtime/default
        container.seccomp.security.alpha.kubernetes.io/frontend: runtime/default
      labels:
        app: {{ .Release.Name -}}-frontend-dep
    spec:
      hostIPC: false
      hostNetwork: false
      hostPID: false
      securityContext:
        runAsUser: 115
        runAsGroup: 125
        fsGroup: 190
        supplementalGroups:
          - 150

      serviceAccountName: default
      containers:
      - name: frontend
        image: {{ include "frontend_image" . }}
        imagePullPolicy: Always

        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          procMount: default
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault

        volumeMounts:
        # - name: react-env
        #   mountPath: /var/www/env
        #   readOnly: true
        # - name: api-redirects
        #   mountPath: /etc/nginx/conf.d
        #   readOnly: true

        - name: log-dir
          mountPath: /var/log/nginx
        - name: body-dir
          mountPath: /var/lib/nginx/body
        - name: proxy-dir
          mountPath: /var/lib/nginx/proxy
        - name: cache-proxy-dir
          mountPath: /var/cache/nginx/proxy_temp
        - name: cache-client-dir
          mountPath: /var/cache/nginx/client_temp
        - name: fast-cgi-dir
          mountPath: /var/cache/nginx/fastcgi_temp
        - name: uwsgi-dir
          mountPath: /var/cache/nginx/uwsgi_temp
        - name: scgi-dir
          mountPath: /var/cache/nginx/scgi_temp
        - name: pid-dir
          mountPath: /var/run

        resources:
          requests:
            memory: {{ required "REQUIRED: frontend.memory.request" .Values.frontend.memory.request }}
            cpu: {{ required "REQUIRED: frontend.cpu.request" .Values.frontend.cpu.request }}
          limits:
            memory: {{ required "REQUIRED: frontend.memory.limit" .Values.frontend.memory.limit }}
            cpu: {{ required "REQUIRED: frontend.cpu.limit" .Values.frontend.cpu.limit }}

        startupProbe:
          httpGet:
            path: /
            port: {{ .Values.frontend.containerPort }}
          failureThreshold: 5
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.frontend.containerPort }}
          initialDelaySeconds: 5
          periodSeconds: 5

        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.frontend.containerPort }}
          initialDelaySeconds: 5
          periodSeconds: 5

        {{- if .Values.firebase.enabled }}
        env:
        - name: FIREBASE_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: firebase-key
        {{- end }}

        ports:
        - containerPort: 80
          name: https
          protocol: TCP
      volumes:
        # - name: react-env
        #   configMap:
        #     name: react-config
        #     items:
        #     - key: env.js
        #       path: env.js
        # - name: api-redirects
        #   configMap:
        #     name: api-config
        #     items:
        #     - key: api.conf
        #       path: api.conf
        - name: log-dir
          emptyDir: {}
        - name: body-dir
          emptyDir: {}
        - name: proxy-dir
          emptyDir: {}
        - name: cache-proxy-dir
          emptyDir: {}
        - name: cache-client-dir
          emptyDir: {}
        - name: fast-cgi-dir
          emptyDir: {}
        - name: uwsgi-dir
          emptyDir: {}
        - name: scgi-dir
          emptyDir: {}
        - name: pid-dir
          emptyDir: {}
{{- end }}
