{{- if and (.Values.enabled) (not .Values.local) }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.external_dns.enabled }}
    external-dns.alpha.kubernetes.io/hostname: {{ include "domain" . -}}.
    {{- end -}}

    {{- if .Values.nginx_ingress.enabled }}
    kubernetes.io/ingress.class: nginx
    {{- if .Values.nginx_ingress.https  }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    {{- end -}}

    {{- else if .Values.google.ingress.enabled }}
    kubernetes.io/ingress.global-static-ip-name: {{ include "ip_name" . }}
    {{- if .Values.google.ingress.https  }}
    networking.gke.io/v1beta1.FrontendConfig: gke-frontendconfig
    networking.gke.io/managed-certificates: google-cert
    {{- end }}
    {{- end -}}

    {{- if .Values.cert_manager.enabled }}
    cert-manager.io/cluster-issuer: "letsencrypt-nginx"
    kubernetes.io/tls-acme: "true"
    {{- end -}}

spec:
  {{- if and (.Values.nginx_ingress.use_tls) (.Values.cert_manager.enabled) }}
  tls:
  - hosts:
    - {{ include "domain" $ }}
    secretName: ingress-certs
  {{- end }}

  {{- if $.Values.nginx_ingress.enabled }}
  rules:
  - host: {{ include "domain" $ }}
    http:
      paths:
      - backend:
          service:
            name: nginx-svc
            port:
              name: http
        path: /
        pathType: Prefix

  {{- else }}

  defaultBackend:
    service:
      {{- if $.Values.nginx.enabled }}
      name: nginx-svc
      port:
        number: 443
      {{- else }}
      name: api-svc
      port:
        number: 80
      {{- end }}
  {{- end }}


{{- end }}

