{{- if and ($.Values.enabled) (not $.Values.local) }}

{{- if $.Values.ingress.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: {{ $.Release.Namespace }}
  annotations:
    {{- if $.Values.external_dns.enabled }}
    external-dns.alpha.kubernetes.io/hostname: {{ include "domain" $ -}}.
    {{- end }}

    {{- if $.Values.nginx_ingress.enabled }}
    kubernetes.io/ingress.class: nginx

    {{- if $.Values.nginx_ingress.https  }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    {{- end }}

    {{- if $.Values.cert_manager.enabled }}
    cert-manager.io/cluster-issuer: "letsencrypt-nginx"
    kubernetes.io/tls-acme: "true"
    {{- end }}

    {{- else if $.Values.google.ingress.enabled }}
    {{- if $.Values.google.ingress.static_ip.enabled }}
    kubernetes.io/ingress.global-static-ip-name: {{ include "ip_name" $ }}
    {{- end }}
    {{- if $.Values.google.ingress.https  }}
    networking.gke.io/v1beta1.FrontendConfig: gke-frontendconfig
    networking.gke.io/managed-certificates: google-cert
    {{- end }}
    {{- end }}
spec:
  {{- if and ($.Values.nginx_ingress.https) ($.Values.cert_manager.enabled) }}
  tls:
  - hosts:
    - {{ include "domain" $ }}
    secretName: ingress-certs
  {{- end }}

  rules:
  {{- if $.Values.nginx_ingress.enabled }}
  - host: {{ include "domain" $ }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name -}}-frontend-svc
            port:
              name: http
        path: /
        pathType: Prefix

  {{- else }}
  - http:
      paths:
      {{- if .Values.backend.enabled }}
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name -}}-backend-svc
            port:
              number: 80
      {{- if .Values.django.enabled }}
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name -}}-backend-svc
            port:
              number: 80
      - path: /accounts
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name -}}-backend-svc
            port:
              number: 80
      {{- end }}
      {{- end }}

      {{- if .Values.frontend.enabled }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name -}}-frontend-svc
            port:
              number: 443
      {{- end }}
  {{- end }}

{{- end }}


{{- end }}

