{{- if and (.Values.enabled) (not .Values.local) }}

{{- if and (.Values.google.ingress.enabled) (.Values.google.ingress.https) }}
{{- if not .Values.cert_manager.enabled }}

apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: google-cert
  namespace: {{ .Release.Namespace }}
spec:
  domains:
    - {{ include "domain" . }}

{{- end }}
{{- end }}

{{- end }}
