{{- if and (.Values.enabled) (.Values.backend.use_pd) }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gce-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ required "REQUIRED: backend.disk_size" .Values.backend.disk_size }}

{{- end }}
