apiVersion: v1
kind: Service
metadata:
  name: argocd-svc

{{- if .Values.ingress }}

  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"ports": {"http":"argocd-backendconfig"}}'
spec:
  type: ClusterIP

{{- else -}}

spec:
  type: LoadBalancer

{{- end }}

  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server




